cafe/urls.py
from django.contrib import admin
from django.urls import path

from .forms import CreateMenuItem
from .views import *

app_name = 'cafe5'

urlpatterns = [
    path('orders/', orders_list, name='all_orders'),
    path('add_order/', add_order, name='add_order'),
    path('order/<int:order_num>', order_details, name='order_details'),
    path('add_new_order', AddOrderView.as_view(), name='add_new_order_by_class_view'),
    path('orders_list/', OrderList.as_view(), name='orders_list_by_class_view'),
    path('o/<int:number>', OrderDetails.as_view(), name='order_details_by_class_view'),
    path('allorders/', AllOrders.as_view(), name='all_orders_generic_view'),
    path('<int:pk>', OrderDetails2.as_view(), name='order_details_generic_view'),
    path('addneworder/', AddNewOrder.as_view(), name='add_new_order_generic_view'),
    path('CreateMenuItem/', form_test.as_view(), name='CreateMenuItem'),

]

test_class/urls.py
from django.contrib import admin
from django.urls import path, include



# import myblog.views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', myblog.views.index),
    # path('register/', myblog.views.register)
    path('cafe5/', include('cafe.urls')),
]

templates/add_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add order</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container-fluid p-3 m-3">
<div class="modal-content w-50 bg-light m-auto p-3">
        <form action="{% url 'cafe5:add_new_order_by_class_view' %}" method="post">
            <h4>add order</h4>
            {% csrf_token %}
            <label for="order_num">order number</label><br>
            <input name="order_number" type="number" id="order_num"><br>
            <label for="status">status</label><br>
            <input name="status" type="text" id="status"><br>
            <label for="timestamp">timestamp</label><br>
            <input name="timestamp" type="datetime-local" id="timestamp"><br>
            <label for="menu_item_id">menu item id</label><br>
            <input name="menu_item_id" type="number" id="menu_item_id"><br>
            <label for="table_number">table number</label><br>
            <input name="table_number" type="number" id="table_number"><br><br>
            <input type="submit">

        </form>
</div>
</div>
</body>
</html>

templates/add_order_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>add orders - generic</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container-fluid p-3 m-3">
    <div class="modal-content w-50 bg-light m-auto p-3">
        <form method="post" action="{% url 'cafe5:add_new_order_generic_view' %}">
            <h4>add order</h4>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    </div>
</div>
</body>
</html>

templates/allorders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>orders list2</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<table class="table table-bordered text-center">
    <tr>
        <th>order number</th>
        <th>order status</th>
        <th>table number</th>
        <th>menu item name</th>
        <th>timestamp</th>
        <th>details</th>


    </tr>
    {% for o in object_list %}
        <tr>
            <td>{{ o.order_number }}</td>
            <td>{{ o.status }}</td>
            <td>{{ o.table_id.table_number}}</td>
            <td>{{ o.menu_item_id.name }}</td>
            <td>{{ o.time_stamp }}</td>
            <td><a  href="{% url 'cafe5:all_orders_generic_view' o.id %}">show order details</a></td>

        </tr>
    {% endfor %}
</table>

</body>
</html>

templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container-fluid">
<table class="table table-bordered text-center">

    <tr>
        <th>order number</th>
        <th>order status</th>
        <th>table number</th>
        <th>table position</th>
        <th>menu item name</th>
        <th>menu item category</th>
        <th>menu item price</th>
        <th>menu item discount</th>
        <th>menu item delivery time</th>
    </tr>

    <tr>
        <td>{{ order_detail.order_number }}</td>
        <td>{{ order_detail.status }}</td>
        <td>{{ order_detail.table_id }}</td>
        <td>{{ order_detail.table_id.cafe_space_position }}</td>
        <td>{{ order_detail.menu_item_id }}</td>
        <td>{{ order_detail.menu_item_id.category }}</td>
        <td>{{ order_detail.menu_item_id.price }}</td>
        <td>{{ order_detail.menu_item_id.discount }}</td>
        <td>{{ order_detail.menu_item_id.serving_time_period }}</td>

    </tr>


    </table>
<button class="btn btn-block btn-outline-secondary"><a href="{% url 'cafe5:orders_list_by_class_view' %}">back to all orders</a></button>
</div>

</body>
</html>

templates/order_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Details</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container-fluid">
<table class="table table-bordered text-center">

    <tr>
        <th>order number</th>
        <th>order status</th>
        <th>table number</th>
        <th>table position</th>
        <th>menu item name</th>
        <th>menu item category</th>
        <th>menu item price</th>
        <th>menu item discount</th>
        <th>menu item delivery time</th>
    </tr>

    <tr>
        <td>{{ o_detail.order_number }}</td>
        <td>{{ o_detail.status }}</td>
        <td>{{ o_detail.table_id }}</td>
        <td>{{ o_detail.table_id.cafe_space_position }}</td>
        <td>{{ o_detail.menu_item_id }}</td>
        <td>{{ o_detail.menu_item_id.category }}</td>
        <td>{{ o_detail.menu_item_id.price }}</td>
        <td>{{ o_detail.menu_item_id.discount }}</td>
        <td>{{ o_detail.menu_item_id.serving_time_period }}</td>

    </tr>


    </table>
<button class="btn btn-block btn-outline-secondary"><a href="{% url 'cafe5:all_orders_generic_view' %}">back to all orders</a></button>
</div>
</body>
</html>

templates/orders_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Orders List</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<table class="table table-bordered text-center">
    <tr>
        <th>order number</th>
        <th>order status</th>
        <th>table number</th>
        <th>menu item name</th>
        <th>timestamp</th>
        <th>details</th>


    </tr>
    {% for o in orders_list %}
        <tr>
            <td>{{ o.order_number }}</td>
            <td>{{ o.status }}</td>
            <td>{{ o.table_id.table_number}}</td>
            <td>{{ o.menu_item_id.name }}</td>
            <td>{{ o.time_stamp }}</td>
            <td><a  href="{% url 'cafe5:order_details_by_class_view' o.id %}">show order details</a></td>

        </tr>
    {% endfor %}
</table>



</body>
</html>

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hadi Komeili Profile</title>
</head>
<body>
<h1>Profile: Hadi Komeili</h1>
<h2>information</h2>
<ul>
    <li style="font-weight: bold;">First Name:</li>Hadi
    <li>Last Name: Komeili</li>
    <li>Phone Number: +989159638625</li>
    <li>e-mail: komeili.hadi@gmail.com</li>
    <li>Gender: Male</li>
</ul>
<h3>Image:</h3>
{% load static %}
<img src="{% static 'download.png' %}" alt="My image">
<h4>Skills:</h4>
<ul>
    <ol type="1">
        <li>Python Programing</li>
        <li>Climbing</li>
        <li>html</li>
    </ol>
</ul>
<h5>Social Media:</h5>
<a href="hnstagram.com">instagram</a>

</body>
</html>

templates/register_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body style="margin: 25px auto;padding: 5px; width:40%;text-align:center; background-color: darkgoldenrod; color: white; border-width: 20px;border-style: solid ;border-radius: 10%">
<h1>
  Register User
</h1>
<h2 style="font-size: large">Enter Your Profile</h2>
<form style=" padding: 50px; text-align: center; background-color: ">
    <label for="fname">First name:</label><br>
    <input type="text" id="fname" name="fname"><br>
    <label for="lname">Last name:</label><br>
    <input type="text" id="lname" name="lname"><br>
    <label for="phone">Phone:</label><br>
    <input type="number" id="phone" name="phone"><br>
    <label for="gender">Choose Gender:</label><br>
    <select id="gender" name="gender">
        <option value="Male">Male</option>
        <option value="Female">Female</option>
    </select><br>

    <label for="address">Address:</label><br>

<textarea id="address" name="address" rows="4" cols="20">
enter address here...
</textarea>

</form>

</body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <table>{{ form.as_table }}
        <input type="submit">
        </table>

{#        <div class="form-control">#}
{#        {{ form.price }}#}
{#        {{ form.Discount }}#}
{#        {{ form.category }}#}
{##}
{#    </div>#}
    </form>
</body>
</html>